# Generated by Django 3.2.8 on 2021-10-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
    ]
