# Generated by Django 3.2.8 on 2021-10-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=120, verbose_name='Customer Name')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('location', models.CharField(blank=True, choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Customer Name')),
                ('datetime', models.DateTimeField()),
                ('time', models.CharField(blank=True, max_length=10, verbose_name='Reservation time')),
                ('partysize', models.IntegerField()),
            ],
        ),
    ]
